"""
Django settings for sixtyfour project.

!!! <NOTICE> !!!

This file is tracked in source control. Only change settings necessary for
all environments to function. Make all environment-specific tweaks (such
as database settings) in 'sixtyfour/local_settings.py'.

!!! </NOTICE> !!!

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3kmp5-wj$i0336s1kft!v8q9bp9*u#xg9n@gw)37x*3j)i@$+@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'user.apps.UserConfig',
    'info.apps.InfoConfig',
    'moderation.apps.ModerationConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'sass_processor',
    'django_registration',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sixtyfour.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['sixtyfour/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
				'sixtyfour.context_processors.all',
				'info.context_processors.all',
            ],
			'builtins': ['sixtyfour.tags'],
        },
    },
]

WSGI_APPLICATION = 'sixtyfour.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = ['user.auth.DefaultBackend']

LOGIN_URL='/login'
LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL='/'

ACCOUNT_ACTIVATION_DAYS = 30
REGISTRATION_SALT = 'djangoRegSalt'

# Email Handling
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# NOTE: Console backend is default for development purposes only
# In production, configure a working email backend in local_settings.py:
# https://docs.djangoproject.com/en/3.0/topics/email/#smtp-backend

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'sixtyfour/static'),
    os.path.join(BASE_DIR, 'node_modules/jquery/dist'),
    os.path.join(BASE_DIR, 'node_modules/bootstrap/dist/js'),
    os.path.join(BASE_DIR, 'node_modules/@fancyapps/fancybox/dist'),
)

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]

NODE_MODULES_URL = STATIC_URL + 'node_modules/'

SASS_PROCESSOR_ROOT = 'sixtyfour/static/compiled'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

DEFAULT_FILE_STORAGE = 'sixtyfour.storage.OverwriteStorage'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

AVATAR_ROOT = ''
AVATAR_URL = ''
BANNER_ROOT = ''
BANNER_URL = ''

LEGACY_SALT_TOKEN = ''

# Default Site Branding.

SITE_NAME = 'sixtyfour'

# Local environment overrides
try:
	from .local_settings import *
except ImportError:
	pass
