# Generated by Django 3.0.7 on 2020-07-04 20:37

from django.conf import settings
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('city', models.CharField(blank=True, max_length=32)),
                ('region', models.CharField(blank=True, max_length=2)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('continent', models.CharField(blank=True, max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(user.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
