# Generated by Django 3.0.7 on 2020-07-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
