# Generated by Django 2.2.4 on 2019-08-11 21:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190805_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Registered Members'), (2, 'Regular Members'), (3, 'Group Members'), (4, 'Only Me')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
