# Generated by Django 2.2.4 on 2019-08-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(max_length=128),
        ),
    ]
