# Generated by Django 3.0.7 on 2020-06-12 20:21

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190813_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Registered Members'), (2, 'Regular Members'), (3, 'Staff Members'), (4, 'Only Me')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(max_length=128, upload_to=user.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(max_length=128, upload_to=user.models.user_banner_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='old_password',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
