# Generated by Django 2.2.4 on 2020-10-09 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200705_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interacted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
