# Generated by Django 4.0.1 on 2022-01-13 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_post_interacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interacted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='PlusOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetType', models.IntegerField(choices=[(1, 'Comment'), (2, 'Post')])),
                ('targetComment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.comment')),
                ('targetPost', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.post')),
                ('user', models.ForeignKey(on_delete=models.SET(user.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('plus_ones', django.db.models.manager.Manager()),
            ],
        ),
    ]
